### ISSUE TITLE
Add "Campaign Name" Field

### ISSUE THREAD

**Issue by nescohen** [sonatype-nexus-community/bbash#6]
Add field to teams and participants to represent which bug bash they are a part of.

Need to update queries to allow selection on this field.

**Comment by bhamail** [comment]
I was able to add a participant with an empty campaign field value. I would have expected the db integrity rules to prevent this, so I think we need a foreign key or something else to make such an operation be rejected by the db.

PUT http://localhost:7777/participant/add
body: { "gitHubName": "bhamail"}

Should'a failed, but created a row in the participant table.

**Comment by bhamail** [comment]
Fixed in by adding `NOT NULL` in  9e249a7b9e995367afd3b48ef1dad6042130d447
